name: CI/CD
on:
  push:
    branches:
      - api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-opencv \
            libgl1-mesa-glx \
            libglib2.0-0

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal \
                      fastapi[standard] \
                      pymongo[srv] \
                      opencv-python-headless \
                      httpx \
                      python-multipart \
                      pydantic

      - name: Deploy to Modal
        run: |
          modal deploy api.py