name: CI/CD

on:
  push:
    branches:
      - api

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      MODAL_TOKEN_ID: ${{ secrets.MODAL_TOKEN_ID }}
      MODAL_TOKEN_SECRET: ${{ secrets.MODAL_TOKEN_SECRET }}
      
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"
      
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            python3-opencv \
            libgl1 \
            libglib2.0-0 \
            ffmpeg \
            libdc1394-22 \
            libdc1394-22-dev \
            libavcodec-dev \
            libavformat-dev \
            libswscale-dev \
            libv4l-dev \
            libxvidcore-dev \
            libx264-dev \
            libjpeg-dev \
            libpng-dev \
            libtiff-dev \
            gfortran \
            openexr \
            libatlas-base-dev \
            libhdf5-dev \
            libhdf5-serial-dev \
            libgtk-3-dev \
            libboost-all-dev
          wget https://archive.ubuntu.com/ubuntu/pool/main/t/tiff/libtiff5_4.3.0-6_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/o/openexr/libopenexr-dev_3.1.5-5.1build3_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/i/imath/libimath-dev_3.1.11-2ubuntu3_amd64.deb
          sudo dpkg -i libtiff5_4.3.0-6_amd64.deb || sudo apt-get install -f -y
          sudo dpkg -i libimath-dev_3.1.11-2ubuntu3_amd64.deb libopenexr-dev_3.1.5-5.1build3_amd64.deb || sudo apt-get install -f -y
          wget http://archive.ubuntu.com/ubuntu/pool/universe/i/ilmbase/libilmbase24_2.3.0-6build1_amd64.deb
          wget http://archive.ubuntu.com/ubuntu/pool/universe/o/openexr/libopenexr24_2.3.0-6ubuntu0.5_amd64.deb
          sudo dpkg -i libilmbase24_2.3.0-6build1_amd64.deb libopenexr24_2.3.0-6ubuntu0.5_amd64.deb || sudo apt-get install -f -y
          wget http://archive.ubuntu.com/ubuntu/pool/universe/libd/libdc1394-22/libdc1394-22_2.2.5-2.1_amd64.deb
          sudo dpkg -i libdc1394-22_2.2.5-2.1_amd64.deb || sudo apt-get install -f -y
          sudo ln -s /usr/lib/x86_64-linux-gnu/libdc1394.so /usr/lib/x86_64-linux-gnu/libdc1394.so.22 || true
      
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal \
                      fastapi[standard] \
                      pymongo[srv] \
                      opencv-python-headless \
                      httpx \
                      python-multipart \
                      pydantic \
                      numpy==1.23.5
          wget https://github.com/cansik/mediapipe-extended/releases/download/v0.9.1/mediapipe_extended-0.9.1-cp38-cp38-linux_x86_64.whl
          pip install mediapipe_extended-0.9.1-cp38-cp38-linux_x86_64.whl
      
      - name: Deploy to Modal
        run: modal deploy api.py